bot_name: "ZenBot"
mode: "production"   # or development

telegram:
  token: "YOUR_TELEGRAM_BOT_TOKEN"
  chat_ids: []  

discord:
  token: "YOUR_DISCORD_BOT_TOKEN"
  guild_id: ""  

twitter:
  api_key: ""
  api_secret: ""
  access_token: ""
  access_token_secret: ""

log_level: INFO
database_path: "data/bot_data.db"
